version: '3.8'

services:
  postgres:
    image: postgres
    container_name: google-trending-now
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - google-trending-now-network

networks:
  google-trending-now-network:

volumes:
  google-trending-now-volume:
